image: markhobson/maven-chrome:jdk-11
stages:
    - repo-clonning
    - data-source-context-based-classification
    - data-classification-levels
variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
    paths:
        - .m2/repository
        - target
Repo-Clonning:
    stage: repo-clonning
    script:
        - pwd
        - git init
        - git clone https://innersource.accenture.com/scm/ethan/ct_complianceascode.git -b keerthana
        - ls -lart
        - cd ct_complianceascode
    artifacts:
        paths:
            - ct_complianceascode/
DataSourceContext-based-classification:
    stage: data-source-context-based-classification
    script:
        - sleep 52
Data-Classification-Levels:
    stage: data-classification-levels
    variables:
        WORKSPACE: "$CI_PROJECT_DIR"
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - ls
        - pwd
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -DsuiteXmlFile=DataClassification.xml
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-ouput/TestReport
