image: markhobson/maven-chrome:jdk-11

stages:
    - repo-clone
    - single-sign-on
    - mfa-authentication
    - session-timeout
    - application-login-authentication

variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
    paths:
        - .m2/repository
        - target

Repo-Cloning:
    stage: repo-clone
    script:
        - pwd
        - git init
        - git clone https://innersource.accenture.com/scm/ethan/ct_complianceascode.git -b keerthana
        - ls -lart
        - cd ct_complianceascode
    artifacts:
        paths:
            - ct_complianceascode/
            
Single sign on:
    stage: single-sign-on
    script:
        - sleep 88

MFA authentication:
    stage: mfa-authentication
    script:
        - sleep 77

Session timeout:
    stage: session-timeout
    script:
        - sleep 77        
            
Application login authentication:
    stage: application-login-authentication
    variables:
        WORKSPACE: "$CI_PROJECT_DIR"
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - ls
        - pwd
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -DsuiteXmlFile=authentication.xml
        - cd `pwd`/test-output/TestReport
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport
            

        
        

