image: markhobson/maven-chrome:jdk-11

stages:
    - repo-clone
    - privileged-access
    - group-access
    - administrative-access    

variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
    paths:
        - .m2/repository
        - target

Repo-Cloning:
    stage: repo-clone
    script:
        - pwd
        - git init
        - git clone https://innersource.accenture.com/scm/ethan/ct_complianceascode.git -b keerthana
        - ls -lart
        - cd ct_complianceascode
    artifacts:
        paths:
            - ct_complianceascode/
                        
Privileged Access:
    stage: privileged-access
    variables:
        WORKSPACE: "$CI_PROJECT_DIR"
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - ls
        - pwd
        - mvn test -DappURL="$URL" -DenterpriseID="$USERNAME" -DenterprisePassword="$PASSWORD" -Dreponame="$Reponame" -DsuiteXmlFile=Privileged_AccessManagement.xml
        - cd `pwd`/test-output/TestReport
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport
            
Group access:
    stage: group-access
    script:
        - sleep 81
            
Administrative access:
    stage: administrative-access
    variables:
        WORKSPACE: "$CI_PROJECT_DIR"
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - ls
        - pwd
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -DsuiteXmlFile=RBAC_testng.xml
        - cd `pwd`/test-output/TestReport
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport
            

        
        

