image: markhobson/maven-chrome:jdk-11

stages:
    - repo-cloning
    - uniqueness

variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
    paths:
        - .m2/repository
        - target
Repo-Cloning:
    stage: repo-cloning
    script:
        - pwd
        - git init
        - git clone https://innersource.accenture.com/scm/ethan/ct_complianceascode.git -b keerthana
        - ls -lart
        - cd ct_complianceascode/

    artifacts:
        paths:
            - ct_complianceascode/
uniqueness:
    stage: uniqueness
    script:
        - cd ct_complianceascode
        - cd Compliance_Check
        - pwd
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -Dldapuname="$ldapuname" -DldapEmail="$ldapemail" -DldapPass="$ldappassword" -DsuiteXmlFile=Uniqueness.xml
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport

