image: markhobson/maven-chrome:jdk-11
stages:
    - repo-cloning
    - password-minimum-length
    - password-maximum-length
    - minimum-2special-characters
    - strong-password
    - password-reset
    - email-based-reset
    - change-default-password
    - password-history-policy

variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
cache:
    paths:
        - .m2/repository
        - target
Repo-Cloning:
    stage: repo-cloning
    script:
        - pwd
        - git init
        - git clone https://innersource.accenture.com/scm/ethan/ct_complianceascode.git -b keerthana
        - ls -lart
        - cd ct_complianceascode
    artifacts:
        paths:
            - ct_complianceascode/
Password-Minimum-Length:
    stage: password-minimum-length
    script:
        - sleep 57
Password-Maximum-Length:
    stage: password-maximum-length
    script:
        - sleep 62
Minimum-2special-Characters:
    stage: minimum-2special-characters
    script:
        - sleep 70
Strong-Password:
    stage: strong-password
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - pwd
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -Dldapuname="$ldapuname" -DldapEmail="$ldapemail" -DldapPass="$ldappassword" -DsuiteXmlFile=passwordComplex_testng.xml
        - cd test-output
        - ls
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport
Password-Reset:
    stage: password-reset
    script:
        - sleep 60
Email-Based-Reset:
    stage: email-based-reset
    script:
        - sleep 77
Change-Default-Password:
    stage: change-default-password
    script:
        - sleep 87
Password-History-Policy:
    stage: password-history-policy
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - ls
        - pwd
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -Dldapuname="$ldapuname" -DldapPass="$ldappassword" -DnewPassword="$newpassword" -DsuiteXmlFile=PasswordHistoryPolicy.xml
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport
