image: markhobson/maven-chrome:jdk-11

stages:
    - repo-clone
    - invalid-parameter-check
    - unauthorized-actions
    - restricted-file-access

variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
    paths:
        - .m2/repository
        - target

Repo-Cloning:
    stage: repo-clone
    script:
        - pwd
        - git init
        - git clone https://innersource.accenture.com/scm/ethan/ct_complianceascode.git -b keerthana
        - ls -lart
        - cd ct_complianceascode
    artifacts:
        paths:
            - ct_complianceascode/
                        
Invalid parameter check:
    stage: invalid-parameter-check
    variables:
        WORKSPACE: "$CI_PROJECT_DIR"
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - ls
        - pwd
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -DsuiteXmlFile=Invalid_Parameter.xml
        - cd `pwd`/test-output/TestReport
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport
    
            
Unauthorized actions:
    stage: unauthorized-actions
    script:
        - sleep 74
            
Restricted file access:
    stage: restricted-file-access
    script:
        - sleep 54
    
            

        
        

