#################################################################################
#                     resources created                                         #
#   Resource Group, Virtual network, security group, Route Table, Subnet        #
#                         Network Interface, Virtual Machine                    #
#################################################################################
---
- hosts: localhost
  connection: local
  tasks: 
   - name: Resource group
     azure_rm_resourcegroup:
       name: AnsibleRG
       location: Southeast Asia
     register: rg
     
   - name: Creating Virtual Network
     azure_rm_virtualnetwork:
       name: AnsibleVN
       resource_group: "{{ rg.state.name }}"
       address_prefixes: "10.0.0.0/16"
     register: Vnet   
       
   - name: Create Security group
     azure_rm_securitygroup:
       name: mySecurityGrp
       resource_group: "{{ rg.state.name }}"
       rules:
         - name: 'AllowSSH'
           protocol: Tcp
           source_address_prefix: '223.186.120.239/32'
           destination_port_range: 22
           access: Allow
           priority: 100
           direction: Inbound
     register: SecGrp
     
   - name: Adding RouteTable
     azure_rm_routetable:
       name: myRouteTable
       resource_group: "{{ rg.state.name }}"
       disable_bgp_route_propagation: False
     register: rt
     
   - name: Create a route
     azure_rm_route:
       name: myRoute
       resource_group: "{{ rg.state.name }}"
       address_prefix: 10.1.0.0/16
       next_hop_type: virtual_network_gateway
       route_table_name: myRouteTable
       
   - name: Adding Subnet
     azure_rm_subnet:
       name: mySubnet
       resource_group: "{{ rg.state.name }}"
       virtual_network: "{{ Vnet.state.name }}"
       address_prefix: "10.0.1.0/24"
       route_table: myRouteTable
       security_group:
         name: "{{ SecGrp.state.name }}"
         resource_group: "{{ rg.state.name }}"
     register: subnet
          
   - name: Create a public ip address
     azure_rm_publicipaddress:
       name: myPublicIp
       resource_group: "{{ rg.state.name }}"
       allocation_method: static
     register: OutputIp
    
   - name: Create a network interface using existing security group and public IP
     azure_rm_networkinterface: 
       name: myNIC
       resource_group: "{{ rg.state.name }}"
       virtual_network: "{{ Vnet.state.name }}"
       subnet: "{{ subnet.state.name }}"
       security_group: "{{ SecGrp.state.name }}"
       ip_configurations:
       - name: ipconfig1
         public_ip_address_name: "{{ OutputIp.state.name }}"
         primary: True 
     register: networkInterface
      
   - name: Create VM
     azure_rm_virtualmachine:
       name: AnsibleVM
       resource_group: "{{ rg.state.name }}"
       vm_size: Standard_DS1_v2
       network_interfaces: "{{ networkInterface.state.id }}"
       admin_username: ansibleAzure
       admin_password: ansibleAzure11
       image:
         offer: UbuntuServer
         publisher: Canonical
         sku: '18.04-LTS'
         version: latest
