- name: Create cloud instances
  hosts: localhost
  vars:
    gcp_project: acn-devopsgcp
    gcp_cred_kind: serviceaccount
    gcp_cred_file : sample
    gcp_region: asia-east1
    
  tasks:
  - name: Creating a new VPC network
    gcp_compute_network:
      name: ansible-network
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
      auto_create_subnetworks: false
    register: network
    
  - name: create a subnetwork
    gcp_compute_subnetwork:
      name: ansible-subnetwork
      network: "{{ network }}"
      region: "{{ gcp_region }}"
      ip_cidr_range: 10.0.10.0/24
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: subnetwork
    
  - name: Create an IPv4 public IP address
    gcp_compute_address:
      name: ansible-address
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: address
  
  - name: create a disk
    google.cloud.gcp_compute_disk:
      name: ansible-disk-instance
      size_gb: 50
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts
      zone: asia-east1-b
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk
    
  - name: create a instance
    gcp_compute_instance:
      name: ansible-instance
      machine_type: n1-standard-1
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      - auto_delete: 'true'
        interface: NVME
        type: SCRATCH
        initialize_params:
          disk_type: local-ssd
      network_interfaces:
      - network: "{{ network }}"
        subnetwork: "{{ subnetwork }}"
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      zone: asia-east1-b
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: AnsibleInstance
      
  - name: Create a firewall
    gcp_compute_firewall:
      name: ansible-firewall
      network: "{{ network }}"
      direction: INGRESS
      allowed:
      - ip_protocol: tcp
        ports:
        - '22'
      target_tags: 
      - "{{ AnsibleInstance.name }}"
      source_ranges: 106.217.71.83/32
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: firewall 
      
  - name: Create a route
    gcp_compute_route:
      name: ansible-route
      dest_range: 10.10.10.0/23
      next_hop_gateway: global/gateways/default-internet-gateway
      network: "{{ network }}"
      tags:
      - "{{ AnsibleInstance.name }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: route