image: markhobson/maven-chrome:jdk-11

stages:
    - repo-clone
    - authentication-logs
    - transaction-logs
    - operations-logs    
    - performance-monitoring
    - network-monitoring
    - app-monitoring

variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
    paths:
        - .m2/repository
        - target

Repo-Cloning:
    stage: repo-clone
    script:
        - pwd
        - git init
        - git clone https://innersource.accenture.com/scm/ethan/ct_complianceascode.git -b keerthana
        - ls -lart
        - cd ct_complianceascode
    artifacts:
        paths:
            - ct_complianceascode/
                        
Authentication logs:
    stage: authentication-logs
    script:
        - sleep 55
            
Transaction logs:
    stage: transaction-logs
    script:
        - sleep 55

Operations logs:
    stage: operations-logs
    script:
        - sleep 50
        
Performance Monitoring:
    stage: performance-monitoring
    script:
        - sleep 70
        
Network Monitoring:
    stage: network-monitoring
    script:
        - sleep 60
            
App Monitoring:
    stage: app-monitoring
    variables:
        WORKSPACE: "$CI_PROJECT_DIR"
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - ls
        - pwd
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -DsuiteXmlFile=LoggingMonitoring.xml
        - cd `pwd`/test-output/TestReport
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport
            

        
        

