apiVersion: v1
kind: Service
metadata:
  name: pythonapp-api
  labels:
    app: pythonapp-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: pythonapp-api
