name: DataMasking
 
on:
  workflow_dispatch:

jobs:   
  job1:  
    name: PII data masking
    if: always()
    runs-on: ubuntu-latest
    steps: 
    - name: Build
      run: sleep 10
      
  job2:  
    needs: job1
    name: Data Scrambling
    if: always()
    runs-on: ubuntu-latest
    steps: 
    - name: Build
      run: sleep 9
    
  job3:  
    name: Data Masking	
    if: always()
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build with Mavev
      run: |
        cd Compliance_Check
        mvn test -DappURL="${{ secrets.APPURL }}" -Dusername="${{ secrets.USERNAME }}" -Dpassword="${{ secrets.PASSWORD }}" -DsuiteXmlFile=Data_Masking.xml
        cd `pwd`/test-output/TestReport
        ls
    - name: Upload report to artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: DataMaskingReport
        path: ${{ github.workspace }}/Compliance_Check/test-output/TestReport/LatestTestReport
        
