name: VulnerabilityManagement

on:
  workflow_dispatch: 

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.8.2
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: '${{ secrets.APPURL }}'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        
      - name: Upload report to artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: VulnerabilityManagement
          path: ${{ github.workspace }}
