image: markhobson/maven-chrome:jdk-11
stages:
    - repo-clonning
    - password-management
variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
    paths:
        - .m2/repository
        - target
Repo-Clonning:
    stage: repo-clonning
    script:
        - pwd
        - git init
        - git clone https://innersource.accenture.com/scm/ethan/ct_complianceascode.git -b keerthana
        - ls -lart
        - cd ct_complianceascode
    artifacts:
        paths:
            - ct_complianceascode/
Password-Management:
    stage: password-management
    variables:
        WORKSPACE: "$CI_PROJECT_DIR"
    script:
        - cd ct_complianceascode
        - ls
        - cd Compliance_Check
        - ls
        - mvn test -DappURL="$appURL" -Dusername="$user_name" -Dpassword="$user_password" -Dldaploginusername="$ldaploginusername" -Dldappassword="$ldappassword" -DsuiteXmlFile=VerifyPasswordEncryption.xml
    artifacts:
        paths:
            - $CI_PROJECT_DIR/test-output/TestReport
